baseURL: 'https://blog.alswl.com/'
languageCode: en-us
title: Log4D
theme: hugo-paper

disqusShortname: blog-alswl-com

params:
  twitter: alswl
  github: alswl
  rss: true
  avatar: alswlx@gmail.com
  name: alswl
  bio: Code Monkey // 擅长江浙菜
  disableHLJS: false
  monoDarkIcon: true

permalinks:
  posts: /:year/:month/:slug/

